export const API_KEY_ERROR_CODE = {
  NOT_FOUND: "APIKEY_NOT_FOUND",
  INVALID: "APIKEY_INVALID",
  PROVIDER_NOT_FOUND: "APIKEY_PROVIDER_NOT_FOUND",
} as const;

export const API_KEY_SUCCESS_CODE = {
  CREATED: "APIKEY_CREATED",
  DELETED: "APIKEY_DELETED",
  FETCHED: "APIKEY_FETCHED",
} as const;
