export const AUTH_SUCCESS_CODE = {
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  EMAIL_VERIFICATION_SENT: "AUTH_EMAIL_VERIFICATION_SENT",
} as const;

export const AUTH_ERROR_CODE = {
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  USER_NOT_VERIFIED: "AUTH_USER_NOT_VERIFIED",
  USER_NOT_AUTHENTICATED: "AUTH_USER_NOT_AUTHENTICATED",
  EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
} as const;
