export const AUTH_SUCCESS_CODE = {
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  EMAIL_VERIFICATION_SENT: "AUTH_EMAIL_VERIFICATION_SENT",
} as const;

export const AUTH_ERROR_CODE = {
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPITRED",
  USER_NOT_VERIFIED: "AUTH_USER_NOT_VERFIED",
  USER_NOT_AUNTHENTICATED: "AUTH_USER_NOT_AUTHENTICATED",
  VERIFIED_TOKEN_EXPIRED: "AUTH_VERIFIED_TOKEN_EXPIRED",
  EMAIL_ALREADY_EXIST: "AUTH_EMAIL_ALREADY_EXIST",
} as const;
