export const AUTH_CODE = {
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  EMAIL_VERIFICATION_SENT: "AUTH_EMAIL_VERIFICATION_SENT",
} as const;
