export const DELIVERY_ERROR_CODE = {
  CREATION_FAILED: "DELIVERY_CREATION_FAILED",
  RETRY_FAILED: "DELIVERY_RETRY_FAILED",
} as const;

export const DELIVERY_SUCCESS_CODE = {
  CREATED: "DELIVERY_CREATED",
  SENT: "DELIVERY_SENT",
  FAILED: "DELIVERY_FAILED",
} as const;
