export const MESSAGE_ERROR_CODE = {
  NOT_FOUND: "MESSAGE_NOT_FOUND",
  CREATION_FAILED: "MESSAGE_CREATION_FAILED",
  INVALID_DATA: "MESSAGE_INVALID_DATA",
} as const;

export const MESSAGE_SUCCESS_CODE = {
  CREATED: "MESSAGE_CREATED",
  FETCHED: "MESSAGE_FETCHED",
} as const;
