export const PROVIDER_ERROR_CODE = {
  NOT_FOUND: "PROVIDER_NOT_FOUND",
  CHANNEL_NOT_SUPPORTED: "PROVIDER_CHANNEL_NOT_SUPPORTED",
  CONFIG_INVALID: "PROVIDER_CONFIG_INVALID",
  CONFIG_MISMATCH: "PROVIDER_CONFIG_MISMATCH",
} as const;

export const PROVIDER_SUCCESS_CODE = {
  CREATED: "PROVIDER_CREATED",
  UPDATED: "PROVIDER_UPDATED",
  DELETED: "PROVIDER_DELETED",
} as const;
